# Generated by Django 3.0.8 on 2021-07-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactManager', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=1000)),
            ],
        ),
    ]
